name: Run Mailer

on:
  push:
    branches: [tdd]
  pull_request:
    branches: [tdd]
  schedule:
    - cron: '0 * * * *'

jobs:
  run-mailer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'  # Specify the PHP version you need

      - name: Install Composer dependencies
        run: composer install

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Run mailer
        env:
          MAILER_SENDER: ${{ secrets.MAILER_SENDER }}
          MAILER_USER: ${{ secrets.MAILER_USER }}
          MAILER_PASSWORD: ${{ secrets.MAILER_PASSWORD }}
        run: |
          go run mailer.go -sender ${{ secrets.MAILER_SENDER }} -user ${{ secrets.MAILER_USER }} -password "${{ secrets.MAILER_PASSWORD }}"